name: flutter_atoms
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "2.0.4"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  state_notifier: 0.7.0
  flutter_state_notifier: 0.7.0
  provider: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.14.1+2
    
flutter:
  uses-material-design: true

